phoronix-test-suite/phoronix-test-suite

pts-core/external-test-dependencies/xml/fedora-packages.xml, pts-core/external-test-dependencies/xml/generic-packages.xml
``libsuperlu3`` is the Debian package name, it should be ``SuperLU-devel``, but
I made it lower case in order to better match the file's conventions.
The generic XML file also has issues with casing - on Fedora at least, the include directory is ``SuperLU`` and it won't detect a properly installed RPM.
I also added ``libsuperlu.so`` to the file checks - according to [rpm.pbone.net], that file name appears to be common across most distros.
=> Fix SuperLU missing dependency issues on Fedora

pts-core/openbenchmarking.org/schemas/types.xsd
Using "https" in a test-profile definition would abort with the error:
```
Errors occurred parsing the main XML.
Element 'ProjectURL': [facet 'pattern'] The value 'https://github.com/StuntsPT/Structure_threader' is not accepted by the pattern 'http://.*'.
```
Instead of changing my URLs to "http" I made this PR.
=> Added support for https in test-profile definitions URLs.

pts-core/objects/phx_graph/phx_graph_core.php
This makes for cleaner rasterization, especially on standard-resolution displays.
=> ceil() calculated translation values to align them to whole pixels

pts-core/objects/phx_graph/phx_graph_core.php, pts-core/objects/phx_graph/phx_graph_horizontal_bars.php
if the stroke comes from a whole number, an odd-number-wide stroke will end half-way across a pixel boundary.
This PR adds a constant half-pixel offset to relevant elements so that their lines fill a single pixel width rather than half of two.
=> Align phx_graph strokes with the pixel grid.

documentation/stubs/01_install.html, documentation/stubs/50_general_information.html, phoronix-test-suite.bat
1. Enhance documentation related to Windows installation
2. Add a "Troubleshooting" section
3. Make some corrections and enhancements to the .bat file.
To expand on item 3. - the original .bat file would not run at all on my Windows 10 systems. I modified the PHP search code to include all subdirectories of C:\Program Files (x86)\PHP\ because the MS Web Platform Installer places PHP in a 'v5.3' subdirectory, which of course is likely to change over time.
=> Add documentation for Windows installation, troubleshooting, and improve .bat file

pts-core/objects/client/pts_client.php, pts-core/objects/client/pts_test_execution.php
This address issue #95 - FullOutput configuration option is added
If set the output of pre/test/interim/post is dumped to stdout
=> Add configuration option to print all test steps

pts-core/modules/graphics_event_checker.php, pts-core/objects/phodevi/phodevi.php
This improves performance of "./phoronix-test-suite help" for example.
=> Run graphics detection only if required

pts-core/modules/matisk.php, pts-core/modules/system_monitor.php
- fixed monitoring results not being properly distinguished between MATISK runs (now without breaking graphs for the normal test process)
- some other minor MATISK and system_monitor bugfixes
=> Monitoring and MATISK fixes

pts-core/modules/phoromatic.php
After set post run context script in phoromatic test schedule, but it doesn't run when testing is over.
=> phoromatic: Fix post run context script

pts-core/external-test-dependencies/scripts/install-arch-packages.sh
It's not necessary to reinstall packages that are already there, `--needed` will skip those
=> pts-core: prevent reinstall of present packages

pts-core/external-test-dependencies/scripts/install-solus-packages.sh, pts-core/external-test-dependencies/xml/solus-packages.xml
Hi Michael,
Have updated the Solus external deps to make it easier for our users in preparation to land PTS in the Solus repo. Thought it'd be a good one to upstream.
su root -c won't work well on Solus as by default you can't login as root until you set a root password. Now it should install the preset test dependencies more easily when the test is installed (seemed to work well for me). I removed csh as zsh wouldn't work with the relevant test profiles.
If there's any issues running the PTS on Solus, or missing deps for profiles feel free to give me a prod and I can fix things up here or look at landing some packages into the repo to improve the testing capabilities. I'll be making sure it runs nicely, but tend to specialise in a smaller number of tests.
Look forward to trying out your …
=> pts-core: Update Solus external dependency handling

pts-core/external-test-dependencies/xml/solus-packages.xml
Hi Michael,
Here's another quick patch to make Solus work great out of the box with the PTS (including the caffe test, though maybe not rbenchmark). It has the new packages to run those BLAS tests that are now in the Solus repo and uses our build essential equivalent. Thought I'd sneak it in before 6.8
I tested in a VM, installing Solus, updating Solus, reboot (for kernel), install PTS and install/run the tests and it sorted itself out all the deps with this new patch. It does give the odd error with the dependency not being met, but all the right packages are installed anyway.
I shall get back to testing those CL avx2 patches and see how they pan out :D
Cheers
=> pts-core: Update latest Solus dependency libs

pts-core/objects/client/pts_tests.php
To ensure they behave like the main executable.
This appears to be the intended behaviour, as globbed arguments aren't as useful as keeping them separate. This may break any tests that rely on that behaviour though, but works for the few that I tried.
This is needed for https://github.com/phoronix-test-suite/test-profiles/pull/2
=> Remove globbing of arguments for pre/interim/post scripts

pts-core/commands/network_info.php, pts-core/objects/pts_network.php
So PTS was getting the first IP/MAC address in the list (which for me was my docker0 device).
I figured the IP and Mac addresses that we actually want is the one associated with the default gateway device.
if the default network interface cannot be determined, the previous behaviour for IP and MAC addresses is used.
=> Network IP+Mac now use default gateway device

pts-core/objects/client/pts_phoroscript_interpreter.php
This fixes https://github.com/phoronix-test-suite/phoronix-test-suite/issues/232:
'Commands in scripts interpreted by phoroscript_interpreter are not executed in a context where the current working directory is set as requested by the script'
This also removes the need of the workaround performed in "install_windows.sh" (https://openbenchmarking.org/innhold/a97d4ee6ea8b6410ca8f739f296f98d5002e05a6 , see "# Note: ...") in https://openbenchmarking.org/test/eliasvan/supertuxkart-1.5.1
Tested with Windows 10, Wine, and Ubuntu 16.04.
=> Set script-requested cwd when executing command

pts-core/modules/flamegrapher.php
Instead of just profiling a sleep of 3 seconds before the test execution,
profile while executing.
Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>
=> pts-core: turn on profiling during test execution

pts-core/objects/client/pts_test_execution.php
This new environment variable may specify a command which can be prepended
into the main test command. One important usage can be when profiling
a certain test and neither flamegrapher nor linux_perf pts-core modules give
us what we want.
Two simple examples on this area
* use /usr/bin/time -v to get some basic stats
$ export EXECUTE_BINARY_PREPEND='/usr/bin/time -v' && \
phoronix-test-suite run ..
* perf-record and leave data (perf.data) in the installed directory
$ export EXECUTE_BINARY_PREPEND='perf record -a -g -F 97 -o perf.data' && \
phoronix-test-suite run ..
NOTE: If either LINUX_PERF or FLAME_GRAPH_PATH environment
variables are present on the environment, EXECUTE_BINARY_PREPEND wont have any
effect.
Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>
=> pts-core: prepend EXECUTE_BINARY_PREPEND in test run request

pts-core/external-test-dependencies/scripts/install-fedora-packages.sh
#268 
Add sudo password prompt alongside root prompt for fedora/centos/rh distributions.
The prompt comes before the `su` attempt.
`su` will still be attempted should the `sudo` password be incorrect.
=> install-fedora-packages.sh: Add sudo password prompt

pts-core/external-test-dependencies/xml/arch-packages.xml
common-dependencies is already added (mesa-demos + unzip)
freeimage is required by universe-x
nothing complained about zlib but name is not zlib1
=> pts-core: Arch deps, fixed zlib name, add freeimage, removed double mesa-demos

pts-core/external-test-dependencies/scripts/install-arch-packages.sh
With this option installed packages will result as 'orphan' for an easy removal when no more needed, this option is already added in the three AUR pkgbuilds
=> install-arch-packages.sh: Add --asdeps option

pts-core/objects/pts_test_option.php
The DefaultEntry is 0 for the system/fio IO Engine, however default-benchmark runs tests with the last engine libaio.
https://github.com/phoronix-test-suite/test-profiles/blob/master/system/fio-1.9.0/test-definition.xml#L58
```
58        <DefaultEntry>0</DefaultEntry>
59        <Menu>
60          <Entry>
61            <Name>POSIX AIO</Name>
62            <Value>posixaio</Value>
63            <Message></Message>
64          </Entry>
65          <Entry>
66            <Name>Sync</Name>
67            <Value>sync</Value>
68            <Message></Message>
69          </Entry>
70          <Entry>
71            <Name>Libaio</Name>
72            <Value>libaio</Value>
73            <Message></Message>
74          </Entry>
75        </Menu>
```
```
% phoronix-test-suite default-benchmark system/fio …
```
=> Fix test option: <DefaultEntry>0</DefaultEntry>

pts-core/objects/client/pts_test_run_manager.php
This change adds a new variable `loop_run_pos` for tracking the current loop that the
test run manager is on. It then uses this new variable in
`get_test_run_position()` so that different pts display modes will be able
to accurately report how far into a run utilizing `TOTAL_LOOP_COUNT` the
test run manager is.
=> pts-core: Fix Loop 'Test i of n' Reporting

pts-core/objects/phodevi/sensors/cpu_temp.php
Fixes cpu.temp reporting on a POWER8 server. Otherwise the wrong
sensor was reported.
=> phodevi: Check more specific ipmitool cpu sensor names first

pts-core/objects/client/pts_test_run_manager.php, pts-core/objects/phodevi/components/phodevi_cpu.php, pts-core/objects/pts_result_file_analyzer.php
This is not the same as the reported cpu thread count from /proc/cpuinfo,
which are kind of virtual cores and don't have uniform numbering. Having the setting clearly displayed is also better than having to divide the threads by cores, even if it was correct.
=> pts-core: Report on the POWER SMT setting in notes

pts-core/objects/pts_Graph/pts_graph_core.php
Measurements are of discrete quantities and thus "Fewer" should be used instead of "Less."
=> minor grammar fix

pts-core/objects/pts_test_run_options.php
The Linux native persistent memory drivers provide `/dev/pmem` entries fsdax and sector type namespaces that can be used to create file systems and be used either as block storage or with a persistent memory aware file system such as ext4 or XFS. 
When using the `auto-disk-mount-points` option in  `test-definition.xml`, it would not display the mounted file systems using /dev/pmem0 and /dev/pmem1. 
```
<Option>
<DisplayName>Disk Target</DisplayName>
<Identifier>auto-disk-mount-points</Identifier>
<ArgumentPrefix></ArgumentPrefix>
<ArgumentPostfix></ArgumentPostfix>
<DefaultEntry></DefaultEntry>
</Option>
```
I saw only the following when running the test suite:
```
1: Default Test Directory
2: /
3: Test All Options
** Multiple items can be selected, delimit by a comma. **
```
With the …
=> Add Persistent Memory disk targets for disk tests

phoronix-test-suite.bat
The PowerShell progress bar makes Invoke-WebRequest dramatically slower than it needs to be.  This adds a command to disable the progress bar, and then re-enable it once the download is complete.
https://stackoverflow.com/questions/28682642/powershell-why-is-using-invoke-webrequest-much-slower-than-a-browser-download
=> Disabling progress bars speeds up Invoke-WebRequest

pts-core/commands/start_result_viewer.php
Hi!
From the commit message:
Currently, giving a pre-defined port to the result-viewer does not work:
**[PROBLEM] Port N is already in use by another server process.**
Since fsockopen returns false on an error [1], the queries must be inverted.
[1] https://www.php.net/manual/de/function.fsockopen.php
BR
bb
=> start_result_viewer: fix server with static port

phoronix-test-suite.bat
vc_redist.x64.exe is still compatible with Visual Studio 2015, 2017 and 2019, see https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
=> phoronix-test-suite.bat: Update VC_redist.x64.exe link to support VS 2019

pts-core/objects/phodevi/components/phodevi_cpu.php, pts-core/objects/phodevi/parsers/phodevi_bsd_parser.php, pts-core/objects/phodevi/parsers/phodevi_osx_parser.php, pts-core/objects/phodevi/sensors/cpu_freq.php, pts-core/objects/phodevi/sensors/sys_power.php
The SPHardwareDataType system profiler query only returns a
marketing string that has no use for us. Use something else when possible.
I was thinking about doing something similar with the flags
(machdep.cpu.features), but the current code is toooo Linux-centric to
play with.
=> macOS: use the actual CPU model, not the 6-core i7 BS

pts-core/commands/start_result_viewer.php
Hello It's me again. I discovered that when the result-viewer is running from systemd, It take whole cpu core.
I found that it is caused by waiting for user input in file pts-core/commands/start_result_viewer.php 
It seems that is caused by that systemd doesn't assign stdin/out pipe for child processes that are executed by the parent command (start-result-viewer daemon) and the while(true) loop running without waiting for input (because there is no stdin pipe).
I solved it by replacing the user input waiting with sleep waiting and now it works ok.
So it would be nice to merge this fix. 
Thanks!
=> Performance fix of systemd daemon result-viewer

pts-core/external-test-dependencies/scripts/install-debian-packages.sh
Fixed stray bracket introduced #495 
Tested, worked for me
```
> phoronix-test-suite run pts/smallpt
...
The following dependencies are needed and will be installed: 
- build-essential
- autoconf
- mesa-utils
- vulkan-utils
- unzip
- apt-file
This process may take several minutes.
debconf: delaying package configuration, since apt-utils is not installed
Reading package lists...
Building dependency tree...
Reading state information...
...
Setting up autoconf (2.69-11) ...
Setting up automake (1:1.16.1-4) ...
update-alternatives: using /usr/bin/automake-1.16 to provide /usr/bin/automake (automake) in auto mode
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for mime-support (3.62) ...
Phoronix Test Suite v10.2.0
To Install:    pts/smallpt-1.2.1
```
=> Fix stray bracket

phoronix-test-suite
This commit modifies the argv handling to work properly with systemd-inhibit. Tested on Solus, where the original argv handling produced an error.
=> Restore systemd-inhibit detection and usage

pts-core/commands/check_tests.php
Checks each test profile to determine the status of the url download.
If successful, a check between the new download and the stored test-profile data
is performed to detect any differences in the filesize, MD5 and SHA256 checksums.
Current http status and any errors are output to a JSON file.
HTTP 302 redirections are also reported.
This test utilizes forking to prevent bottlenecks.
A file for a given url is downloaded once and reused for future tests thus preventing
multiple downloads of the same file.
=> Add new command to download and check each test-profile

pts-core/modules/phoromatic.php, pts-core/objects/client/pts_logger.php
Adds logging of the non-idle commands coming from the
Phoromatic Server.
Adjust log date to include timedate by moving to ISO8601 format date
Include backtrace information to identify function, file and line for
log messages
=> pts-core: Add debug commands & improve logging

pts-core/commands/result_file_to_pdf.php, pts-core/objects/client/pts_client.php
Use a generic name for export when referring to a test file via
filename vs assuming that the parameter is a test result identifier.
=> [pts-core] Result export by file should use a generic name

pts-core/modules/perf_tips.php
Reword the message to avoid confusion with the "powersave" governor
and only print the message if a governor is actually available.
=> perf_tips: Improve governor tip 

pts-core/objects/phoromatic/phoromatic_server.php
Longstanding bug when converting the base 16 sha1 to base 36 encoding for pprid.  Recent versions of php seem to be complaining about this to stdout.  This fixes a regression in log file uploading for phoromatic.
=> pts-core:  Fix bug converting from sha1 to base 36 in compute_pprid

pts-core/objects/pts_result_file_system.php
When uploading to Phoromatic, the system logs are staged after simplifying
the identifier with pts_strings::simplify_string_for_file_handling().
Closes #577
=> pts-core: Include alternate path for system-logs for result viewer

pts-core/external-test-dependencies/dependency-handlers/microsoft_dependency_handler.php, pts-core/objects/phodevi/components/phodevi_system.php
Fixes https://github.com/phoronix-test-suite/phoronix-test-suite/issues/465.
Currently `cygwin` etc. are saved to `%USERPROFILE%\Downloads`, but this is a user-configurable path.
=> Windows: use known folder for downloads directory

pts-core/objects/phodevi/components/phodevi_system.php
Query `HKLM\Software\Microsoft\Windows NT\CurrentVersion` for `CurrentMajorVersionNumber`, `CurrentMinorVersionNumber` and `UBR` (Windows 10+) and `CurrentBuild` and `CurrentVersion` (Windows 8.1 and earlier) to populate the kernel version. Particularly with Windows 11, Microsoft has been making changes in regular patches that significantly impact benchmarks, such as the L3 cache fix for AMD processors included in [22000.282](https://support.microsoft.com/en-us/topic/october-21-2021-kb5006746-os-build-22000-282-preview-03190705-0960-4ba4-9ee8-af40bef057d3).
Example Windows 11 kernel version: `10.0.22000.376` (previously `10.0`)
Example Windows 7 kernel version: `6.1.7601` (previously `6.1`)
=> Windows: Include update build revision (UBR) in kernel version

pts-core/external-test-dependencies/xml/generic-packages.xml
Fix Perl Interface to the MD5 Algorithm FileCheck for RHEL 8/9 and CentOS Stream 8/9.
Signed-off-by: Jiri Mencak <jmencak@users.noreply.github.com>
=> Fix Perl Interface to the MD5 Algorithm FileCheck

pts-core/external-test-dependencies/xml/fedora-packages.xml
I'm unsure whether this is the right way to fix the dependency issues, but the PR does solve them in this way.  Unfortunately, the 3 test profiles that depend on these two packages still fail to install properly, at least on RHEL8.  I'll look into that a bit more as time allows.  One of the issues seemed to be Python 3.7 dependency, the other one was a missing downloadable tarball.
=> Fix python-numpy and python-scipy deps for Fedora

pts-core/objects/phodevi/components/phodevi_gpu.php
Remove $this_ratio calculation that would cause divide by zero errors.  Does not appear to be used
anywhere and causes errors when the GPU provides only one mode.
Unreproduced failure, but appears safe.
=> phodevi: Remove mode ratio calculation

pts-core/commands/network_info.php, pts-core/objects/pts_network.php
Fix the behavior of pts_network::is_proxy_setup() for #745
- in `network-info` command, use fixed is_proxy_setup() instead of directly comparing return value of get_network_proxy().
- trivial fix: 'Automatic conversion of false to array is deprecated' warning
=> fix: is_proxy_setup() should return 'true' if the proxy is set

install_macos
Restore argument to `sed` that was removed in #469. `install_macos` never completes without the argument.
=> Restore sed argument

pts-core/objects/phodevi/phodevi.php, pts-core/objects/pts_env.php
This option allows to specify additional architecture support to being able to install tests that supports specific architecures only. It can be useful in systems where is available an user-space emulator (e.g. FEX-EMU for x86_64 applications on aarch64) to run binary tests that cannot be compiled natively.
The introduced environment variable is HOST_EXTRA_COMPATIBLE_ARCH.
=> Add environment option for extra architecture support 

pts-core/objects/phodevi/sensors/cpu_power.php
psys domain is a system domain which aggregates all system power. This requires hardware support and configuration by OEMs. There can be multiple psys domains in servers. psys domains are present at the same level as package domains in the powercap/intel-rapl sysfs. This is not just CPU related power.
For CPU power sensor just use package level without adding energy values from psys domains. So, skip adding psys energy value to $total_energy.
=> Ignore psys domain for CPU power sensor

pts-core/objects/client/pts_external_dependencies.php
This fix adds in the /opt/ directories to search for dependencies when using Homebrew installed natively on ARM64 macOS to the $possible_paths  in pts_external_dependencies.php
=> Update pts_external_dependencies.php - ARM64 Homebrew dependency fix

pts-core/objects/phodevi/components/phodevi_cpu.php
LoongArch processors uses the "Model Name:" field in /proc/cpuinfo to denote the processor model, a snippet below:
```
processor               : 31
package                 : 0
core                    : 31
global_id               : 31
CPU Family              : Loongson-64bit
Model Name              : Loongson-3C6000
CPU Revision            : 0x10
FPU Revision            : 0x00
CPU MHz                 : 2200.00
BogoMIPS                : 4400.00
TLB Entries             : 2112
Address Sizes           : 48 bits physical, 48 bits virtual
ISA                     : loongarch32r loongarch32s loongarch64
Features                : cpucfg lam ual fpu lsx lasx crc32 complex crypto lspw lvz lbt_x86 lbt_arm lbt_mips
Hardware Watchpoint     : yes, iwatch count: 8, dwatch count: 4
```
Add "Model Name" to …
=> phodevi_cpu: add LoongArch processor detection support

pts-core/objects/pts_test_result_parser.php
Some benchmark output reports are in the format:
xyz score:XYZ
Here there is no space between ':' and actual result.
To parse such format create a template something like this: <OutputTemplate>xxx:#_RESULT_#</OutputTemplate>
This type of the format can't be parsed correctly.
The current implementation expects a "space" after column. For example:
In test-profiles/system/selenium-1.0.18/results-definition.xml <ResultsParser>
<OutputTemplate>WEBXPRT SCORE RESULT: #_RESULT_#</OutputTemplate>
To be able to parse when there is no space between ":" and "#" add a a space character in the template line.
=> pts-core: Parsing result format with ":#_RESULT_#"

pts-core/objects/pts_svg_dom_gd.php
Hi there,
A small fix to make the background for PNG transparent. Otherwise, it is filled with black which looks odd.
Thanks
=> Make PNG background transparent. It's black by default
